name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --push \
          --file Dockerfile \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/jenkins-lab3-github-actions-task:latest \
          .
